version: '3'
services:
  frontend:
    image: 'frontend'
    container_name: 'frontend'
    ports:
      - 4200:4200
    links:
      - backend
  backend:
    image: 'backend'
    container_name: 'backend'
    ports:
      - 8081:8081
    links:
      - database
    environment:
      - SPRING_DATA_MONGODB_HOST=database
      - SPRING_DATA_MONGODB_DATABASE=seaplol
      - SPRING_DATA_MONGODB_USER=root
      - SPRING_DATA_MONGODB_PASSWORD=U9O!VI4XMn!8
