version: '3'
services:
  frontend:
    image: 'frontend'
    container_name: 'frontend'
    ports:
      - 4200:4200
    links:
      - backend
  backend:
    network_mode: host
    image: 'backend'
    container_name: 'backend'
    ports:
      - 8081:8081
